language: go
# cannot install golint for go version 1.8.x and lower
go:
  - 1.11.x
env:
  - GO111MODULE=on
os:
  - linux
# Windows don't know how to build using Makefile
script:
  - go build cmd/goconfig/main.go
  - go test ./...
